name: Deploy frontend
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker build -t bonfirebooks/react-test -f ./docker/Dockerfile.dev .
      - run: docker run bonfirebooks/react-test npx vitest run

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: dokcer-test-app
          environment_name: docker-test-app-env
          existing_bucket_name: elasticbeanstalk-ap-northeast-2-489391668825 
          region: ap-northeast-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip